dist: xenial
sudo: required

# See https://github.com/MUME/MMapper/blob/master/.travis.yml

git:
  depth: 1

language: cpp

matrix:
  include:
    - name: OSX
      os: osx
      osx_image: xcode10.2
      compiler: clang
      addons:
        homebrew:
          packages:
            - cmake
            - qt5
            - clang-format
            - miniupnpc
            - lcov
            - openssl
      env:
        - MATRIX_EVAL=""
        - CLANG_FORMAT=clang-format

    - name: Windows
      language: shell
      os: windows

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt-5.12.3-xenial'
          packages:
            - g++-8
            - clang-format-6.0
            - cmake
            - libminiupnpc-dev
            - lcov
            - mesa-common-dev
            - qt512-meta-full
      env:
        - QT=512 MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - CLANG_FORMAT=clang-format-6.0

# Windows builds are experimental in Travis and are unreliable, do not force it.
allow_failures:
  - os: windows

before_install:
  - eval "${MATRIX_EVAL}"
  - '[ "$TRAVIS_OS_NAME" != windows ] || sh ../Scripts/installQt.sh'
  - '[ "$TRAVIS_OS_NAME" != windows ] || cmd.exe /C 'cd && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"'

install:
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt5'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export PATH=/usr/local/opt/qt5/bin:$PATH'
  - qmake -v

before_script:
  # Linux
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[ "$TRAVIS_OS_NAME" != linux ] || . /opt/qt$QT/bin/qt$QT-env.sh'
  # Mac
  - '[[ "$TRAVIS_OS_NAME" != osx || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[ "$TRAVIS_OS_NAME" != osx ] || export MMAPPER_CMAKE_EXTRA=-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl'
  # TODO check clang info
  - mkdir build
  - '[[ "$TRAVIS_OS_NAME" != osx || "$TRAVIS_OS_NAME" != linux ]] || cd build'
  - '[[ "$TRAVIS_OS_NAME" != osx || "$TRAVIS_OS_NAME" != linux ]] || cmake --version'
  - '[ "$TRAVIS_OS_NAME" != windows ] || dir build'
#  - cmake .. $MMAPPER_CMAKE_EXTRA -DUSE_CODE_COVERAGE=true

script:
  - echo "${PWD}"
  - '[ "$TRAVIS_OS_NAME" != osx ] || chmod +x ../Scripts/build_osx.sh'
  - '[ "$TRAVIS_OS_NAME" != osx ] || sh ../Scripts/build_osx.sh'
  - '[ "$TRAVIS_OS_NAME" != linux ] || chmod +x ../Scripts/build_linux.sh'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sh ../Scripts/build_linux.sh'
  - '[ "$TRAVIS_OS_NAME" != windows ] || echo "Hello from Windows World"'


